# Generated by Django 5.2 on 2025-04-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('subtext', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='perks/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
