# Generated by Django 5.2 on 2025-04-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='tours/')),
                ('rating', models.CharField(max_length=50)),
                ('booked', models.CharField(max_length=50)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_private', models.BooleanField(default=False)),
            ],
        ),
    ]
