# Generated by Django 5.2 on 2025-04-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='booked',
        ),
        migrations.AddField(
            model_name='tour',
            name='booking_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tour',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tour',
            name='rating',
            field=models.FloatField(),
        ),
    ]
