# Generated by Django 5.2 on 2025-04-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_tour_booked_tour_booking_count_tour_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='link',
        ),
        migrations.AddField(
            model_name='tour',
            name='badge',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(upload_to='tour_images/'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
