# Generated by Django 5.2 on 2025-04-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_tour_link_tour_badge_alter_tour_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedTour',
            fields=[
            ],
            options={
                'verbose_name': 'Featured Tour',
                'verbose_name_plural': 'Featured Tours',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.tour',),
        ),
        migrations.CreateModel(
            name='PrivateTour',
            fields=[
            ],
            options={
                'verbose_name': 'Private Tour',
                'verbose_name_plural': 'Private Tours',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.tour',),
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_type',
            field=models.CharField(choices=[('featured', 'Featured Tour'), ('private', 'Private Tour')], default='featured', max_length=20),
        ),
    ]
