# Generated by Django 5.2 on 2025-04-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_featuredtour_delete_privatetour_delete_tour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredtour',
            name='slug',
            field=models.SlugField(default='default-slug', unique=True),
        ),
    ]
