# Generated by Django 5.2 on 2025-04-12 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_featuredtour_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredtour',
            name='slug',
        ),
    ]
