# Generated by Django 5.2 on 2025-04-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_featuredtour_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredtour',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
