# Generated by Django 5.2 on 2025-04-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_featuredtour_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatetour',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
