# Generated by Django 5.2 on 2025-04-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_privatetour_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredtour',
            name='detail_page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='privatetour',
            name='detail_page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
