# Generated by Django 5.2 on 2025-04-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_featuredtour_detail_page_privatetour_detail_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredtour',
            name='detail_page',
            field=models.CharField(blank=True, choices=[('tour_detail_half_day.html', 'Half Day Land Rover Trip'), ('tour_detail_full_day.html', 'Full Day Land Rover Trip'), ('tour_detail_private_group.html', 'Private Group Adventure')], help_text="Optional: Select a detail page template to link this tour's 'Book' button", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='privatetour',
            name='detail_page',
            field=models.CharField(blank=True, choices=[('tour_detail_half_day.html', 'Half Day Land Rover Trip'), ('tour_detail_full_day.html', 'Full Day Land Rover Trip'), ('tour_detail_private_group.html', 'Private Group Adventure')], help_text="Optional: Select a detail page template to link this tour's 'Book' button", max_length=100, null=True),
        ),
    ]
