# Generated by Django 5.2 on 2025-04-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_privatetour_detail_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatetour',
            name='detail_page',
            field=models.CharField(blank=True, choices=[('tour_detail_half_day.html', 'Half Day Land Rover Trip'), ('tour_detail_full_day_land_rover.html', 'Full Day Land Rover Trip'), ('tour_detail_private_group.html', 'Private Group Adventure'), ('tour_detail_private_half_day.html', 'Private Half Day Tour'), ('tour_detail_full_day_private.html', 'Full Day Private Tour'), ('tour_detail_sunrise_half_day.html', 'Sunrise + Half Day Tour')], help_text="Optional: Select a detail page template to link this tour's 'Book' button", max_length=100, null=True),
        ),
    ]
