# Generated by Django 5.2 on 2025-04-13 08:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_privatetour_detail_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredtour',
            name='highlights',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='featuredtour',
            name='itinerary',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='featuredtour',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='featuredtour',
            name='service_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='featuredtour',
            name='terms_conditions',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='featuredtour',
            name='detail_page',
            field=models.CharField(blank=True, choices=[('tour_detail_half_day.html', 'Half Day Land Rover Trip'), ('tour_detail_full_day_land_rover.html', 'Full Day Land Rover Trip'), ('tour_detail_intimate_group.html', ' Intimate Group Adventure'), ('tour_detail_full_day_private.html', 'Full Day Private Tour')], help_text="Optional: Select a detail page template to link this tour's 'Book' button", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='privatetour',
            name='detail_page',
            field=models.CharField(blank=True, choices=[('tour_detail_half_day_coral_hill.html', 'Half Day Trip - Coral Hills'), ('tour_detail_private_half_day.html', 'Private Half Day Tour'), ('tour_detail_sunrise_half_day.html', 'Sunrise + Half Day Tour')], help_text="Optional: Select a detail page template to link this tour's 'Book' button", max_length=100, null=True),
        ),
    ]
