# Generated by Django 5.2 on 2025-04-13 08:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_featuredtour_highlights_featuredtour_itinerary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredtour',
            name='about_this_tour',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='featuredtour',
            name='departure_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
