# Generated by Django 5.2 on 2025-04-15 03:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_featuredtour_about_this_tour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredtour',
            name='essentials',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='featuredtour',
            name='locations',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
