# Generated by Django 5.2 on 2025-04-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='price',
            field=models.DecimalField(decimal_places=2, default=89.0, max_digits=10),
            preserve_default=False,
        ),
    ]
