# Generated by Django 5.2 on 2025-04-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_transfer_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='title',
        ),
        migrations.AddField(
            model_name='transfer',
            name='from_city',
            field=models.CharField(default='Thrissur', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='to_city',
            field=models.CharField(default='kochi', max_length=100),
            preserve_default=False,
        ),
    ]
