# Generated by Django 5.2 on 2025-04-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_transfer_title_transfer_from_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='from_city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='to_city',
            field=models.CharField(default='', max_length=255),
        ),
    ]
