# Generated by Django 5.2 on 2025-04-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_transfer_from_city_alter_transfer_to_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='from_city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='to_city',
            field=models.CharField(max_length=255),
        ),
    ]
