# Generated by Django 5.2 on 2025-04-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_transfer_from_city_alter_transfer_to_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
