# Generated by Django 5.2 on 2025-04-20 06:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_transfer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatetour',
            name='about_this_tour',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privatetour',
            name='departure_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='privatetour',
            name='essentials',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privatetour',
            name='highlights',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privatetour',
            name='itinerary',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privatetour',
            name='locations',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privatetour',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privatetour',
            name='service_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privatetour',
            name='terms_conditions',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
