# Generated by Django 5.2 on 2025-04-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_privatetour_about_this_tour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredtour',
            name='child_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price per child (age 3–7)', max_digits=10),
        ),
        migrations.AddField(
            model_name='privatetour',
            name='child_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price per child (age 3–7)', max_digits=10),
        ),
    ]
