# Generated by Django 5.2 on 2025-04-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_featuredtour_child_price_privatetour_child_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='pickup_type',
            field=models.CharField(choices=[('hotel', 'Hotel Pickup – user enters address'), ('default', 'Default Pickup – show predefined location')], default='hotel', help_text='Choose whether this transfer uses hotel address input or a fixed pickup location.', max_length=20),
        ),
    ]
