# Generated by Django 5.2 on 2025-04-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_transfer_pickup_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
