# Generated by Django 5.2 on 2025-04-26 04:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_transferbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferbooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
