# Generated by Django 5.2 on 2025-04-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_transferbooking_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='child_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
