# Generated by Django 5.2 on 2025-04-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_featuredtour_min_travelers_privatetour_min_travelers'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredtour',
            name='max_bookings_per_day',
            field=models.IntegerField(default=10, help_text='Maximum bookings allowed per day'),
        ),
        migrations.AddField(
            model_name='privatetour',
            name='max_bookings_per_day',
            field=models.IntegerField(default=10, help_text='Maximum bookings allowed per day'),
        ),
    ]
