# Generated by Django 5.2 on 2025-04-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_transferavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredtour',
            name='start_time',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AddField(
            model_name='privatetour',
            name='start_time',
            field=models.TimeField(default='08:00'),
        ),
    ]
