# Generated by Django 5.2 on 2025-05-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_transfer_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='max_bookings_per_day',
            field=models.IntegerField(default=10, help_text='Maximum bookings allowed per day'),
        ),
    ]
